def operation():
    print("Enter 2 number:")
    a=int(input())
    b=int(input())
    print("addition:",(a+b))
    print("substraction:",(a-b))
    print("multiplication:",(a*b))
    print("division:",(a//b))
    print("mod:",(a%b))
operation()